### ISSUE TITLE
Ruby, Gems, DevKit, Bundler ...... to get Caffe2?

### ISSUE THREAD

**Issue by crunch3** [caffe2/caffe2.github.io#29]
Any chance we could just (preferably) use Conda or (less conveniently) a Cygwin shell script instead?  To build Bundler, you must install Ruby (e.g. 2.6.1.1), Gems AND the Ruby devkit - that's a TON of stuff just to build an installer, not to mention that "ruby dk.rb init" (part of the Ruby install) fails on Windows 10, so you can't build Ruby which you need to build Bundler which you then need to build Caffe2.

Seriously?  Must installing Caffe2 on Windows really depend on SO many other things, each with their own real and potential installation issues?  Maybe we can reengineer the electrical grid, the BIOS, rewrite some microcoded instructions, and some portion of the OS while we're at it?  It shouldn't be this hard and don't even mention compiling from source - that almost always has a ton of it's own blockades to success.  Ia no one curating suggested install procedures before publication?  At the moment, I don't even need GPU support - just plain Jane CPU only Caffe2 for Python 3.7 on Windows 10.  Why is this so hard?

**Comment by pjh5** [comment]
A few things:

1. This is the repo for the Caffe2 documentation, not Caffe2. This repo has all these dependencies to generate all the docs and make a pretty website. Users not should never need this code for anything. The actual Caffe2 code was at https://github.com/caffe2/caffe2
2. Caffe2 has been merged into Pytorch and now lives at https://github.com/pytorch/pytorch . The Caffe2 code is being reused in Pytorch so that we could combine Pytorch's intuitive frontend with Caffe2's heavily optimized backend. This means that this particular repo https://github.com/caffe2/caffe2 is no longer maintained, but all the code lives on, can still be built, and is still usable in https://github.com/pytorch/pytorch.
3. Pytorch has nightly binaries every night, for windows too. You can find installation instructions for windows here https://pytorch.org/get-started/locally/
